apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_Host: bX1zcWw== #mysql
  DB_User: cm7ffss== #root
  DB_Password: ecd7gfF7g== #paswrd



# Command to create encoded strings
# echo -n 'mysql' | base64
# kubectl get secret
#kubectl describe secret
#kubectl get secret app-secret -o yaml
# Command to decode encoded strings
# echo -n 'bX1zcWw==' | base64 --decode
